name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Style checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1

      - name: Import order (isort)
        run: poetry run isort --profile=black --check --diff .

      - name: Code style (black)
        run: poetry run black --check --diff .

      - name: Semantic checks (flake8)
        run: poetry run flake8
